[package]
name = "notebook"
version = "0.0.0"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}

[addresses]
StarcoinFramework = "0x1"
nangongamo = "0xdeEC22DdD4cA1CbAF9baa73844e2376F"