[package]
name = "blockchain-pos"
version = "0.1.0"
edition = "2021"
author = "Yu Chen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3" 
crypto-hash = "0.3.4" 

