[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"
author = "Yu Chen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0.86"
sha2 = "0.10.6"